FROM practica-spark:latest

USER root

# Airflow y el provider de Spark
ENV AIRFLOW_HOME=/opt/airflow
RUN pip install --no-cache-dir "apache-airflow==2.9.3" apache-airflow-providers-apache-spark==4.7.1

WORKDIR /opt/airflow

EXPOSE 8080

# Copia el script de arranque
COPY resources/airflow/start_airflow.sh /start_airflow.sh
RUN chmod +x /start_airflow.sh

CMD ["/start_airflow.sh"]